---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jeffrey.
--- DateTime: 8/8/24 3:40 PM
---

function love.conf(t)
    t.window.title = "Space Shooter"
    t.window.width = 640
    t.window.height = 480
end