---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jeffrey.
--- DateTime: 8/13/24 8:07 PM
---

require("mod.pool")
Background = Object:extend()

function Background:new()
    self.stars = Pool(20)
    for i=1,20 do
        self.stars:append({
            x = math.random() * SCREEN_X,
            y = (math.random() * (SCREEN_Y - HUD_HEIGHT)) + HUD_HEIGHT,
            vel = math.random(60, 240)
        })
    end
end

function Background:update(dt)
    for _,v in ipairs(self.stars.pool) do
        -- Get star velocity and add to pos
        v.x = v.x - v.vel * dt
        if v.x < -16 then v.x = SCREEN_X + 16 end
    end
end

function Background:draw()
    love.graphics.setColor(1,1,1)
    for _,v in ipairs(self.stars.pool) do
        love.graphics.rectangle("fill", v.x, v.y, 1, 1)
    end
end