---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jeffrey.
--- DateTime: 8/12/24 12:40 PM
---

require("mod.entity")
EnemyBullet = Entity:extend()

function EnemyBullet:new(x, y, pool)
    self.super:new()
    self.sprite = love.graphics.newImage("asset/sprite/e_bullet.png")
    self.owner = pool
    self.x = x or 0
    self.y = y or 0
    self.width = 8
    self.height = 4
    self.x_speed = -256
    self.y_speed = 0
end

function EnemyBullet:update(dt)
    self.super.update(self, dt)

    -- Check collisions
    local res = self:handleCollision(gPlayer)
    if res == true and gPlayer.state ~= -1 then
        gPlayer:destroy()
        self.owner:remove_at(self.rid)
    end

    -- Check if off screen
    if self.x < -16 then
        self.owner:remove_at(self.rid)
    end
end

function EnemyBullet:draw()
    self.super.draw(self)
end