---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jeffrey.
--- DateTime: 8/8/24 8:00 PM
---

require("mod.entity")
EnemyDud = Entity:extend()

function EnemyDud:new(x, y)
    EnemyDud.super:new()
    self.x = x or 0
    self.y = y or 0
    self.x_speed = -80
    self.y_speed = 0
    self.width = 16
    self.height = 16
    self.sprite = love.graphics.newImage("asset/sprite/enemy_dud.png")
    self.boom = love.graphics.newImage("asset/sprite/boom.png")

    self.dead = false
    self.e_timer = 0
    self.e_end = 1
end

function EnemyDud:update(dt)
    self.super.update(self, dt)

    -- Check if off screen
    if self.x < -16 then
        gEnemies:remove_at(self.rid)
    end

    -- Check e_timer
    if self.dead == true then
        self.e_timer = self.e_timer + dt
    end
    if self.e_timer >= self.e_end then
        gEnemies:remove_at(self.rid)
    end
end

function EnemyDud:draw()
    self.super.draw(self)
end

function EnemyDud:destroy()
    self.dead = true
    self.sprite = self.boom
    self.x_speed = 0
    gPoints = gPoints + 100
    forcePlay(sfxBoom)
end