---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jeffrey.
--- DateTime: 8/8/24 8:00 PM
---

require("mod.entity")
EnemyDud = Entity:extend()

local STATE_TRAVEL = 0
local STATE_HONE   = 1
local STATE_BACK   = 2
local STATE_DEAD   = 3

local SPEED        = 80

function EnemyDud:new(x, y)
    EnemyDud.super:new()
    self.state = STATE_TRAVEL
    self.x = x or 0
    self.y = y or 0
    self.x_speed = -SPEED
    self.y_speed = 0
    self.width = 16
    self.height = 16
    self.sprite = love.graphics.newImage("asset/sprite/enemy_dud.png")
    self.boom = love.graphics.newImage("asset/sprite/boom.png")

    self.dead = false
    self.e_timer = 0
    self.e_end = .5
end

function EnemyDud:update(dt)
    self.super.update(self, dt)

    switch(self.state) {
        [STATE_TRAVEL] = function()
            -- Check if adjacent to player
            if self.x < gPlayer.x then
                -- Check y relative to player
                local ny = 0
                if self.y > gPlayer.y then ny = -SPEED * 1.2
                else                       ny = SPEED * 1.2 end

                -- Set speed and state
                self.state = STATE_HONE
                self.y_speed = ny
                self.x_speed = 0
            end
        end,
        [STATE_HONE] = function()
            -- Check if bordering on screen edge
            if self.y >= SCREEN_Y - 16 or self.y <= HUD_HEIGHT + 16 then
                -- Time to go back lol
                self.state = STATE_BACK
                self.y_speed = 0
                self.x_speed = SPEED
            end
        end,
        [STATE_BACK] = function()
            -- Check if we're off screen
            if self.x >= SCREEN_X + 16 then gEnemies:remove_at(self.rid) end
        end,
        [STATE_DEAD] = function()
            -- Increment death timer
            self.e_timer = self.e_timer + dt
            if self.e_timer >= self.e_end then gEnemies:remove_at(self.rid) end
            -- Do not check for collisions with player
            return
        end
    }

    -- Check collisions with player
    local res = self:handleCollision(gPlayer)
    if res == true then
        -- BYE BYE
        gPlayer:destroy()
    end
end

function EnemyDud:draw()
    self.super.draw(self)
end

function EnemyDud:destroy()
    -- Set values
    self.state = STATE_DEAD
    self.dead = true
    self.x_speed = 0
    self.y_speed = 0
    self.sprite = self.boom
    forcePlay(sfxBoom)

    -- Add points
    addPoints(100)
end
