---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jeffrey.
--- DateTime: 8/12/24 11:32 AM
---

--- Floats around the edge of the screen and
--- shoots at the player.

require("mod.entity")
EnemyShooter = Entity:extend()

