---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jeffrey.
--- DateTime: 8/8/24 3:47 PM
---

Entity = Object.extend(Object)

function Entity.new(self)
    self.rid = 0
    self.x = 0
    self.y = 0
    self.width = 0
    self.height = 0
    self.x_speed = 0
    self.y_speed = 0
    self.max_speed = 0
    self.sprite = love.graphics.newImage("asset/sprite/temp.png")
end

function Entity.update(self, dt)
    self.y = self.y + self.y_speed * dt
    self.x = self.x + self.x_speed * dt
end

function Entity.draw(self)
    love.graphics.setColor(1, 1, 1)
    love.graphics.draw(self.sprite, self.x - self.width / 2, self.y - self.height / 2)
end

-- Handles collision checking between self and provided object
function Entity.handleCollision(self, obj)
    local s_left = self.x - self.width / 2
    local s_right = self.x + self.width / 2
    local s_up = self.y - self.height / 2
    local s_down = self.y + self.height / 2

    local o_left = obj.x - obj.width / 2
    local o_right = obj.x + obj.width / 2
    local o_up = obj.y - obj.height / 2
    local o_down = obj.y + obj.height / 2

    if s_right > o_left
    and s_left < o_right
    and s_down > o_up
    and s_up < o_down then
        return true
    end
    return false
end