---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jeffrey.
--- DateTime: 8/8/24 5:14 PM
---

require("mod.entity")
PlayerBullet = Object.extend(Entity)

function PlayerBullet.new(self, x, y)
    Entity.super.new(self)
    self.sprite = love.graphics.newImage("asset/sprite/p_bullet.png")
    self.x = x or 0
    self.y = y or 0
    self.width = 8
    self.height = 4
    self.x_speed = 324
    self.y_speed = 0
end

function PlayerBullet.update(self, dt)
    self.super.update(self, dt)

    -- Check collisions
    for i,v in ipairs(gEnemies.pool) do
        local res = self.handleCollision(self, v)
        if res == true and v.state ~= -1 then
            v:destroy()
            gPlayerBullets:remove_at(self.rid)
        end
    end

    -- Check if off screen
    if self.x > SCREEN_X + 16 then
        gPlayerBullets:remove_at(self.rid)
    end
end

function PlayerBullet.draw(self)
    self.super.draw(self)
end