---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jefftastic.
--- DateTime: 8/8/24 12:28 PM
---

require("mod.entity")
require("mod.player_bullet")
Player = Entity:extend()

-- Initialize constants
local STATE_ALIVE const = 0
local STATE_DEAD const = 1

-- Returns a player object
function Player.new(self)
    Player.super.new(self)
    self.sprite = love.graphics.newImage("asset/sprite/player.png")
    self.state = STATE_ALIVE
    self.x = 32
    self.y = SCREEN_Y / 2
    self.width = 16
    self.height = 16
    self.x_input = 0
    self.y_input = 0
    self.max_speed = 150
end

-- Update player based on input, collide
function Player.update(self, dt)
    -- Generate speed, if applicable
    self.updateSpeed(self, dt)

    -- Move based on input
    self.super.update(self, dt)

    -- Clamp position on screen
    self.x = math.max(16, math.min(self.x, SCREEN_X / 3))
    self.y = math.max(16, math.min(self.y, SCREEN_Y - 16))
end

-- Update player visuals
function Player.draw(self)
    self.super.draw(self)
end

function Player.input(self, scancode)
    -- Get vector of movement
    self.y_input = -booltonum(love.keyboard.isDown("up")) + booltonum(love.keyboard.isDown("down"))
    self.x_input = -booltonum(love.keyboard.isDown("left")) + booltonum(love.keyboard.isDown("right"))

    -- Check for shooting
    if scancode == "z" then
        -- Create a bullet at our position
        local b = PlayerBullet(self.x, self.y)
        b.x = self.x
        b.y = self.y

        -- Add to pool
        local res = gPlayerBullets:append(b)
        if res == true then
            -- Play sound effect
            forcePlay(sfxShoot)
        end
    end
end

-- Manages speed values
function Player.updateSpeed(self, dt)
    self.x_speed = self.x_speed + ((self.max_speed * self.x_input) - self.x_speed) * (12 * dt)
    self.y_speed = self.y_speed + ((self.max_speed * self.y_input) - self.y_speed) * (12 * dt)
end

-- Converts bool into a number
function booltonum(b)
    return b and 1 or 0
end