---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jeffrey.
--- DateTime: 8/8/24 5:39 PM
---

--- Manages a table of items, never letting the table
--- exceed a predefined limit

Pool = Object:extend()

function Pool:new(maximum)
    -- Initialize
    self.pool = {}
    self.count = 0
    self.limit = maximum or 0
end

-- Adds a new element to pool
function Pool:append(value)
    -- Check size of pool
    if self.count == self.limit then
        return false
    end

    -- Add to pool
    table.insert(self.pool, value)
    self.count = self.count + 1
    value.rid = self.count
    return true
end

-- Removes element from pool at position
function Pool:remove_at(pos)
    -- Check if in bounds
    if pos > self.limit then
        return
    end

    -- Remove element at position
    table.remove(self.pool, pos)
    self.count = self.count - 1

    -- Reassign RID
    for i, v in ipairs(self.pool) do
        v.rid = i
    end
end